// AUTO-GEGENEREERD door scratchpad/gen-roll-products.mjs
// Bron: Quiz/src/data/woocommerce-product-ids.ts (STICKER/POUCH) + Intake/src/data/roll-colors.ts (naam<->id).
// Kleur -> WooCommerce sample-product-ID's + kleurnaam -> kleur-id, voor de "Advies afgerond"-cartlinks.

export const SAMPLE_STICKER_IDS: Record<string, number> = {
  "blank-page": 9023,
  "sugar-whip": 9026,
  "rock-rocket": 9040,
  "feather-flow": 9041,
  "grey-gatsby": 9042,
  "stone-tone": 9043,
  "shadow-nap": 9044,
  "mist-dream": 9045,
  "chill-whisper": 9046,
  "cool-story": 9047,
  "onyx-dip": 9048,
  "dark-ash": 9049,
  "shut-eye": 9050,
  "sage-blink": 9051,
  "dawn-fog": 9052,
  "leaf-love": 9053,
  "hidden-depths": 9054,
  "breeze-in": 9055,
  "sweet-horizon": 9056,
  "deep-dive": 9057,
  "fizzy-drizzle": 9058,
  "ice-breaker": 9059,
  "denim-days": 9060,
  "sky-sofa": 9061,
  "daydream-dip": 9062,
  "navy-baby": 9063,
  "night-plunge": 9064,
  "easy-does": 9065,
  "tide-twist": 9066,
  "lost-orbit": 9067,
  "olive-wink": 9068,
  "home-safari": 9069,
  "pistache-please": 9070,
  "moss-boss": 9071,
  "field-trip": 9072,
  "lawn-order": 9302,
  "daily-om": 9303,
  "quiet-wild": 9304,
  "old-forest": 9305,
  "couch-crush": 9306,
  "bubble-gum": 9307,
  "flirt-alert": 9308,
  "pinky-promise": 9309,
  "berry-nice": 9310,
  "hot-shot": 9311,
  "peach-out": 9313,
  "dulce-glow": 9314,
  "cozy-cotta": 9315,
  "milky-lilac": 9316,
  "dear-diary": 9317,
  "fable-mystic": 9318,
  "sunny-cheerio": 9319,
  "honey-drop": 9320,
  "strike-gold": 9321,
  "cherry-on": 9322,
  "monk-mood": 9323,
  "fudgy-brownie": 9327,
  "fresh-sheets": 13796,
  "milk-foam": 13797,
  "lazy-linen": 13798,
  "snooze-button": 13799,
  "early-bird": 13800,
  "cashmere-cloud": 13801,
  "off-duty": 13802,
  "sand-salute": 13803,
  "powder-puff": 13804,
  "cuddle-mode": 13805,
  "soft-landing": 13806,
  "sandy-toes": 13807,
  "morning-mist": 13808,
  "zen-den": 13809,
  "sunday-sweater": 13810,
  "taupe-notch": 13811,
  "group-hug": 13812,
  "siesta-fiesta": 13813,
  "tan-lines": 13814,
  "snug-life": 13815,
  "fired-up": 13816,
  "teddy-bear": 13817,
  "spiced-latte": 13818,
  "desert-date": 13819
};

export const SAMPLE_POUCH_IDS: Record<string, number> = {
  "blank-page": 9329,
  "sugar-whip": 9332,
  "rock-rocket": 9346,
  "feather-flow": 9347,
  "grey-gatsby": 9348,
  "stone-tone": 9349,
  "shadow-nap": 9350,
  "mist-dream": 9351,
  "chill-whisper": 9352,
  "cool-story": 9353,
  "onyx-dip": 9354,
  "dark-ash": 9355,
  "shut-eye": 9356,
  "sage-blink": 9357,
  "dawn-fog": 9358,
  "leaf-love": 9359,
  "hidden-depths": 9360,
  "breeze-in": 9361,
  "sweet-horizon": 9362,
  "deep-dive": 9363,
  "fizzy-drizzle": 9364,
  "ice-breaker": 9365,
  "denim-days": 9366,
  "sky-sofa": 9367,
  "daydream-dip": 9368,
  "navy-baby": 9369,
  "night-plunge": 9370,
  "easy-does": 9371,
  "tide-twist": 9372,
  "lost-orbit": 9373,
  "olive-wink": 9374,
  "home-safari": 9375,
  "pistache-please": 9376,
  "moss-boss": 9377,
  "field-trip": 9378,
  "lawn-order": 9455,
  "daily-om": 9456,
  "quiet-wild": 9457,
  "old-forest": 9458,
  "couch-crush": 9459,
  "bubble-gum": 9460,
  "flirt-alert": 9461,
  "pinky-promise": 9462,
  "berry-nice": 9463,
  "hot-shot": 9464,
  "peach-out": 9466,
  "dulce-glow": 9467,
  "cozy-cotta": 9468,
  "milky-lilac": 9469,
  "dear-diary": 9470,
  "fable-mystic": 9471,
  "sunny-cheerio": 9472,
  "honey-drop": 9473,
  "strike-gold": 9474,
  "cherry-on": 9475,
  "monk-mood": 9476,
  "fudgy-brownie": 9480,
  "fresh-sheets": 13820,
  "milk-foam": 13821,
  "lazy-linen": 13822,
  "snooze-button": 13823,
  "early-bird": 13824,
  "cashmere-cloud": 13825,
  "off-duty": 13826,
  "sand-salute": 13827,
  "powder-puff": 13828,
  "cuddle-mode": 13829,
  "soft-landing": 13830,
  "sandy-toes": 13831,
  "morning-mist": 13832,
  "zen-den": 13833,
  "sunday-sweater": 13834,
  "taupe-notch": 13835,
  "group-hug": 13836,
  "siesta-fiesta": 13837,
  "tan-lines": 13838,
  "snug-life": 13839,
  "fired-up": 13840,
  "teddy-bear": 13841,
  "spiced-latte": 13842,
  "desert-date": 13843
};

// Kleurnaam (lowercase, getrimd) -> kleur-id.
export const COLOR_NAME_TO_ID: Record<string, string> = {
  "blank page": "blank-page",
  "sugar whip": "sugar-whip",
  "rock rocket": "rock-rocket",
  "feather flow": "feather-flow",
  "grey gatsby": "grey-gatsby",
  "stone tone": "stone-tone",
  "shadow nap": "shadow-nap",
  "mist dream": "mist-dream",
  "chill whisper": "chill-whisper",
  "cool story": "cool-story",
  "onyx dip": "onyx-dip",
  "dark ash": "dark-ash",
  "shut eye": "shut-eye",
  "sage blink": "sage-blink",
  "dawn fog": "dawn-fog",
  "leaf love": "leaf-love",
  "hidden depths": "hidden-depths",
  "breeze in": "breeze-in",
  "sweet horizon": "sweet-horizon",
  "deep dive": "deep-dive",
  "fizzy drizzle": "fizzy-drizzle",
  "ice breaker": "ice-breaker",
  "denim days": "denim-days",
  "sky sofa": "sky-sofa",
  "daydream dip": "daydream-dip",
  "navy baby": "navy-baby",
  "night plunge": "night-plunge",
  "easy does": "easy-does",
  "tide twist": "tide-twist",
  "lost orbit": "lost-orbit",
  "olive wink": "olive-wink",
  "home safari": "home-safari",
  "pistache please": "pistache-please",
  "moss boss": "moss-boss",
  "field trip": "field-trip",
  "lawn order": "lawn-order",
  "daily om": "daily-om",
  "quiet wild": "quiet-wild",
  "old forest": "old-forest",
  "couch crush": "couch-crush",
  "bubble gum": "bubble-gum",
  "flirt alert": "flirt-alert",
  "pinky promise": "pinky-promise",
  "berry nice": "berry-nice",
  "hot shot": "hot-shot",
  "peach out": "peach-out",
  "dulce glow": "dulce-glow",
  "cozy cotta": "cozy-cotta",
  "milky lilac": "milky-lilac",
  "dear diary": "dear-diary",
  "fable mystic": "fable-mystic",
  "sunny cheerio": "sunny-cheerio",
  "honey drop": "honey-drop",
  "strike gold": "strike-gold",
  "cherry on": "cherry-on",
  "monk mood": "monk-mood",
  "fudgy brownie": "fudgy-brownie",
  "fresh sheets": "fresh-sheets",
  "milk foam": "milk-foam",
  "lazy linen": "lazy-linen",
  "snooze button": "snooze-button",
  "early bird": "early-bird",
  "cashmere cloud": "cashmere-cloud",
  "off duty": "off-duty",
  "sand salute": "sand-salute",
  "powder puff": "powder-puff",
  "cuddle mode": "cuddle-mode",
  "soft landing": "soft-landing",
  "sandy toes": "sandy-toes",
  "morning mist": "morning-mist",
  "zen den": "zen-den",
  "sunday sweater": "sunday-sweater",
  "taupe notch": "taupe-notch",
  "group hug": "group-hug",
  "siesta fiesta": "siesta-fiesta",
  "tan lines": "tan-lines",
  "snug life": "snug-life",
  "fired up": "fired-up",
  "teddy bear": "teddy-bear",
  "spiced latte": "spiced-latte",
  "desert date": "desert-date"
};

export const SHOP_BASE = "https://roll.nl";

export function colorNameToId(name: string): string | null {
  return COLOR_NAME_TO_ID[(name ?? "").trim().toLowerCase()] ?? null;
}

// Bouwt een multi_add cart-URL uit id:qty-paren, of null als er niets is.
export function multiAddUrl(pairs: [number, number][], goto: "cart" | "checkout" = "cart"): string | null {
  if (!pairs.length) return null;
  const spec = pairs.map(([id, qty]) => `${id}:${qty}`).join(",");
  return `${SHOP_BASE}/?multi_add=${spec}&goto=${goto}`;
}

// ── Opvolgmail-producten (fase: producten in de opvolgmail) ────────────────
// Sample-pack -> WooCommerce product-id (uit Quiz/src/data/woocommerce-product-ids.ts).
export const PACK_PRODUCT_IDS: Record<string, number> = {
  "wit-sample-pack": 6902, "lichtbeige-sample-pack": 13917, "beige-sample-pack": 6873, "greige-sample-pack": 6897,
  "lichtgrijs-sample-pack": 6904, "donkergrijs-sample-pack": 6907, "grijsgroen-sample-pack": 6956, "lichtgroen-sample-pack": 6951,
  "donkergroen-sample-pack": 6958, "diep-groenblauw-sample-pack": 6960, "lichtblauw-sample-pack": 6955, "donkerblauw-sample-pack": 6959,
  "roze-sample-pack": 6946, "oranje-sample-pack": 6949, "paars-sample-pack": 6950, "geel-sample-pack": 6957,
  "rood-sample-pack": 6948, "bruin-sample-pack": 6961,
};

// Prijzen (indicatief, zoals in de kleurmatch-mail). Als strings voor directe weergave.
export const PRICE = { sticker: "€ 2,50", tester: "€ 7,-", pack: "€ 10,-" };
export const PRICE_NUM = { sticker: 2.5, tester: 7, pack: 10 };

// Publieke Supabase-storage met de productbeelden (zelfde bucket als de mailbeelden).
const IMG_BASE = "https://lsboujprrvhntgbvlvyu.supabase.co/storage/v1/object/public/sample-images";
export const sampleImage = (kind: "pack" | "sticker" | "tester", id: string) => {
  const dir = kind === "pack" ? "packs" : kind === "sticker" ? "stickers" : "pouches";
  return `${IMG_BASE}/${dir}/${id}.png`;
};
